version: "3"
services:
  redis:
    image: redis:latest
    container_name: redisTD
    ports:
      - "6381:6379"
  db:
    image: postgres
    container_name: postgresT
    ports:
      - "5431:5432"
    volumes:
      - ./pg_data:/var/liv/postgressql/data/pgdata
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
      PGDATA: /pg_data:/var/liv/postgressql/data/pgdata
